### PR TITLE
fix: unstoppable domains lookup fix

### PR DESCRIPTION
**Pull request by amritkumarj**

### CODE REVIEW

**Comment by monokh** [comment]
Hey @amritkumarj 

Could you please explain the purpose of the latest changes?

**Comment by amritkumarj** [comment]
@monokh This PR resolves polygon issue

**Comment by monokh** [comment]
> @monokh This PR resolves polygon issue

👍 
Is this still draft or ready to go now?

**Comment by amritkumarj** [comment]
@monokh Ready to go!

**Pull request merged**
